plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.projekatmobilne'
    compileSdk 36

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withInputStream { localProperties.load(it) }
    }

    defaultConfig {
        applicationId "com.example.projekatmobilne"
        minSdk 30
        targetSdk 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "ONESIGNAL_REST_API_KEY", "\"${localProperties.getProperty('ONESIGNAL_REST_API_KEY', '')}\""

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui

    // Kalendar
    implementation 'com.github.prolificinteractive:material-calendarview:2.0.1'

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // ============ FIREBASE ============
    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'

    // ============ LIFECYCLE (ViewModels) ============
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.8.7'

    // ============ QR KOD (ZXing) ============
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'

    // ============ CHARTS ============
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    // ============ Kalendar moment ============
    implementation 'com.jakewharton.threetenabp:threetenabp:1.4.4'

    // ============ ONESIGNAL (Notifikacije) ============
    implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}

apply plugin: 'com.google.gms.google-services'